version: '3'

services:
  server:
    container_name: server
    image: huriellopes/php-nginx
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    ports:
      - 80:80
    networks:
      - feegow

  database:
    container_name: db
    image: postgres:9.6
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YOUR_PASSWORD"
      POSTGRES_DB: "DATABASE_NAME"
    restart: always
    #    ports:
    #      - 5432:5432
    networks:
      - feegow

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - feegow

networks:
  feegow:
